---
- hosts: localhost
  roles:
    - homebrew
    - amethyst
    - google_chrome
    - hyper
    - ruby
    - dotfiles
    - the_silver_searcher
    - virtualbox
    - vagrant
    - packer
    - docker
  tasks:
  - name: install docker
    homebrew:
      name: docker
      state: present
  - name: install docker-machine
    homebrew:
      name: docker-machine
      state: present
  - name: install postman
    homebrew_cask:
      name: postman
      state: present
  - name: install atom
    homebrew_cask:
      name: atom
      state: present
  - name: install npm
    homebrew:
      name: npm
      state: present
  - name: install spotify
    homebrew_cask:
      name: spotify
      state: present
  - name: install slack
    homebrew_cask:
      name: slack
      state: present
  - name: install skype
    homebrew_cask:
      name: skype
      state: present
  - name: install steam
    homebrew_cask:
      name: steam
      state: present
