---
- hosts: localhost
  roles:
    - homebrew
    - amethyst
    - google_chrome
    - hyper
    - ruby
    - dotfiles
    - the_silver_searcher
    - virtualbox
    - vagrant
    - packer
    - docker
    - postman
    - npm
    - spotify
    - slack
  - name: install skype
    homebrew_cask:
      name: skype
      state: present
  - name: install steam
    homebrew_cask:
      name: steam
      state: present
