---
- hosts: localhost
  roles:
    - homebrew
    - amethyst
    - google_chrome
  tasks:
  - name: install hyper terminal
    homebrew_cask:
      name: hyper
      state: present
  - name: install ruby-build
    homebrew:
      name: ruby-build
      state: present
  - name: install rbenv
    homebrew:
      name: rbenv
      state: present
  - name: copy ~/.bash_profile
    copy:
      src: ../../dotfiles/.bash_profile
      dest: ~/.bash_profile
  - name: install the_silver_searcher
    homebrew:
      name: the_silver_searcher
      state: present
  - name: copy git config
    copy:
      src: ../../dotfiles/.gitconfig
      dest: ~/.gitconfig
  - name: install virtualbox
    homebrew_cask:
      name: virtualbox
      state: present
  - name: install vagrant
    homebrew_cask:
      name: vagrant
      state: present
  - name: install packer
    homebrew:
      name: packer
      state: present
  - name: install docker
    homebrew:
      name: docker
      state: present
  - name: install docker-machine
    homebrew:
      name: docker-machine
      state: present
  - name: install postman
    homebrew_cask:
      name: postman
      state: present
  - name: install atom
    homebrew_cask:
      name: atom
      state: present
  - name: check ruby 2.4 installed
    shell: rbenv versions | grep 2.4
    register: ruby_2_4_check
  - name: install ruby 2.4
    shell: rbenv install 2.4.0
    when: ruby_2_4_check.stdout == ""
  - name: install npm
    homebrew:
      name: npm
      state: present
  - name: copy hyper config
    copy:
      src: ../../dotfiles/.hyper.js
      dest: ~/.hyper.js
  - name: install spotify
    homebrew_cask:
      name: spotify
      state: present
  - name: install slack
    homebrew_cask:
      name: slack
      state: present
  - name: install skype
    homebrew_cask:
      name: skype
      state: present
  - name: install steam
    homebrew_cask:
      name: steam
      state: present
